; This program has been generated by the pyosdevlib Python library
; and is not intended to be edited
; 
start:
    mov ax, 10
    mov bx, 25
    add bx, ax
    mov dx, bx
    jmp label2
substract:
    mov ax, 8
    mov bx, 7
    sub ax, bx